# see https://www.mkdocs.org/user-guide/configuration/
# Project information
site_name: Obsidian + MkDocs Template
site_url: https://cxplonka.github.io/obsidian-sandbox-mkdocs/
site_author: Christian Plonka
site_description: >-
  Obsidian help vault build with MkDocs and use the Material theme
  
# Repository
repo_name: cxplonka/obsidian-sandbox-mkdocs
repo_url: https://github.com/cxplonka/obsidian-sandbox-mkdocs
edit_uri: edit/main/docs/

# Copyright
copyright: Made with ❤️ by Christian

theme:
    name: 'material'
    locale: en
    custom_dir: .overrides
    favicon: 'assets/images/favicon.ico'
    
    features: # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.highlight
    - search.suggest
    - search.share
    - navigation.footer
    - content.code.copy
    - content.action.view
    - content.action.edit
    
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://cxplonka.github.io/
    - icon: fontawesome/brands/github
      link: https://github.com/cxplonka

# Extensions
markdown_extensions:
  - pymdownx.highlight: # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
      linenums: true
      anchor_linenums: true
      use_pygments: true # pyments not work with mermaid
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - admonition
  - nl2br
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vega-lite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
        - name: vega
          class: vega
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vega
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - mdx_truly_sane_lists # better lists
  - mdx_breakless_lists # https://github.com/adamb70/mdx-breakless-lists
  # - markdown_captions # image caption support

  - toc:
      permalink: true

plugins:
  - charts
  - tags
  # https://blueswen.github.io/mkdocs-glightbox/
  - glightbox:
      auto_caption: true # img caption-alt https://pypi.org/project/mkdocs-glightbox/
  # https://pypi.org/project/mkdocs-callouts/
  - callouts
  - search:
      indexing: 'full'
  - roamlinks
  - mermaid2
  # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: true
  # https://github.com/apenwarr/mkdocs-exclude
  - exclude:
      regex:
        - .*slide.*.md
  # https://github.com/timvink/mkdocs-git-authors-plugin
  - git-authors

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
#  - https://unpkg.com/mermaid/dist/mermaid.min.js
